import { ListView, LineEdit } from "std-widgets.slint";
import { AppPalette } from "palette.slint";
import {MyText} from "commons.slint";

export struct SlintCalendarEvent{
    uid: string,
    title: string,
    begin_day: int,
    day_of_week: string,
    begin_time: string,
    end_time: string,
}

export struct DateInfo {
    row_idx: int,
    col_idx: int,
    day-of-month: int,
    has-event: bool,
}

export component CalendarView inherits HorizontalLayout{
    in-out property <[SlintCalendarEvent]> events: []; //should be loaded on the current month
    in-out property <[DateInfo]> days: []; //same as above
    in-out property <int> month; //same as above
    in-out property <int> year; //same as above
    in-out property <int> days-in-month; //same as above
    in-out property <string> month_name; //same as above
    in-out property <bool> is-editing-event: false;
    in-out property <bool> is-adding-event: false;
    in-out property <string> selected-uid;
    in-out property <string> selected-title;


/* add_event(title-input.text, day-input.text.to-float(), month-input.text.to-float(), year-input.text.to-float(),
                            beg-hour.text.to-float(), beg-min.text.to-float(), end-hour.text.to-float(), end-min.to-float()); */

    callback add_event(string, int, int, int, int, int, int, int);
    callback change_event(string, string, int, int, int, int, int, int, int);
    callback get_events(int, int);
    callback delete_event(string);

    //We make the left handside thing
    VerticalLayout {
        padding-top: -50px;
        padding-left: 10px;
        width: 500px;
        if is-adding-event == false && is-editing-event == false : ListView {
            in-out property <int> previous-day: 0;
            for data[index] in events : VerticalLayout {
                width: parent.width;
                if index == 0 || data.begin_day != events[index - 1].begin_day : VerticalLayout {
                    MyText {
                        height: 25px;
                        text: data.day_of_week + ", " + month_name + " " + data.begin_day + ".";
                    }
                    Rectangle {
                        background: AppPalette.is-dark ? #dedede : #4e4e4e; // Color of the line
                        height: 1px;         // Thickness of the line
                        vertical-stretch: 0; // Prevents the line from expanding vertically
                    }
                }
                HorizontalLayout {
                    padding: 5px;
                    in-out property <string> uid: data.uid;
                    Rectangle{
                        horizontal-stretch: 0;
                        background: AppPalette.primary-color;
                        width: 1px;
                    }
                    get-old-title := MyText {
                        padding-left: 15px;
                        vertical-alignment: center;
                        text: data.title;
                        width: 100px;
                    }
                    VerticalLayout {
                        MyText{text: data.begin_time;}
                        MyText{text: data.end_time;}
                    }
                    Rectangle{
                        padding-right: 10px;
                        in-out property <string> uid : parent.uid;
                        background: AppPalette.secondary-color;
                        MyText {text: "Edit event";}
                        width: 100px;
                        height: 30px;
                        border-radius: 5px;
                        border-color: self.background.darker(30%);
                        TouchArea {
                            clicked => {
                                selected-uid = parent.uid;
                                selected-title = get-old-title.text;
                                is-editing-event = true;
                            }
                        }
                    }
                    Rectangle{
                        in-out property <string> uid : parent.uid;
                        background: #b30b0b;
                        width: 100px;
                        height: 30px;
                        border-radius: 5px;
                        border-color: self.background.darker(30%);
                        MyText {text: "Delete event";}
                        TouchArea {
                            clicked => {
                                delete_event(parent.uid);
                            }
                        }
                    }
                }
            }
        }
        if is-adding-event : addEvent := VerticalLayout {
            spacing: 10px;
//--------------Title
            HorizontalLayout {
                MyText {text: "Event title:"; vertical-alignment: center;}
                title-input := LineEdit {
                    placeholder-text: "My event"; 
                    width: 250px;
                    height: 30px;
                }
            }
//---------------Date
            HorizontalLayout {
                MyText {text: "Date:";vertical-alignment: center;}
                addEventMain := HorizontalLayout {
                    out property <int> year: year-input.text.to-float();
                    out property <int> month: month-input.text.to-float();
                    out property <int> day: day-input.text.to-float();

                    out property <int> max-days: 
                    month == 2 ? (is-leap-year ? 29 : 28) :
                    (month == 4 || month == 6 || month == 9 || month == 11) ? 30 : 31;

                    private property <bool> is-leap-year: 
                        mod(year, 4) == 0 && (mod(year, 100) != 0 || mod(year, 400) == 0);

                    in-out property <bool> is-valid-date:
                    year-input.text.character-count == 4 &&
                    year >= 2026 && year <=  2100 &&
                    month >= 1 && month <= 12 && day >= 1 && day <= max-days;

                    day-input := LineEdit {
                        placeholder-text: "DD";
                        width: 80px;
                        height: 30px;
                    }
                    month-input := LineEdit {
                        placeholder-text: "MM";
                        width: 80px;
                        height: 30px;
                    }
                    year-input := LineEdit {
                        placeholder-text: "YYYY";
                        width: 80px;
                        height: 30px;
                    }
                }
            }
            HorizontalLayout {
                MyText {text: "Starts:";vertical-alignment: center;}
                beg-input := HorizontalLayout {
                    in-out property <int> hours: beg-hour.text.to-float();
                    in-out property <int> mins: beg-hour.text.to-float();
                    in-out property <bool> is-valid:
                    hours >= 0 && hours < 24 
                    && mins >= 0 && mins < 60;

                    beg-hour := LineEdit {
                        width: 80px;
                        height: 30px;
                        placeholder-text: "hh";
                    }
                    
                    beg-min := LineEdit {
                        width: 80px;
                        height: 30px;
                        placeholder-text: "mm";
                    }
                }
            }
            HorizontalLayout {
                MyText {text: "Ends:";vertical-alignment: center;}
                end-input := HorizontalLayout {
                    in-out property <int> hours: beg-hour.text.to-float();
                    in-out property <int> mins: beg-hour.text.to-float();
                    in-out property <bool> is-valid:
                    hours >= 0 && hours < 24 
                    && mins >= 0 && mins < 60;

                    end-hour := LineEdit {
                        placeholder-text: "hh";
                        width: 80px;
                        height: 30px;
                    }
                    
                    end-min := LineEdit {
                        width: 80px;
                        height: 30px;
                        placeholder-text: "mm";
                    }
                }
            } 
            addSubmit := Rectangle {
                MyText {text: beg-input.is-valid && end-input.is-valid && addEventMain.is-valid-date ?
                    "Submit" : "Incorrect format";}
                background: beg-input.is-valid && end-input.is-valid && addEventMain.is-valid-date ? 
                AppPalette.secondary-color : #c82323;
                border-radius: 5px;
                width: 100px;
                height: 30px;
                TouchArea {
                    clicked => {
                        if(beg-input.is-valid && end-input.is-valid && addEventMain.is-valid-date){
                            add_event(title-input.text, day-input.text.to-float(), month-input.text.to-float(), year-input.text.to-float(),
                                beg-hour.text.to-float(), beg-min.text.to-float(), end-hour.text.to-float(), end-min.text.to-float());
                            is-adding-event = false;
                        }
                    }
                }
            }
            Rectangle {
                MyText {text: "Cancel"; horizontal-alignment: center;}
                background: AppPalette.primary-color ;
                border-radius: 5px;
                width: 60px;
                height: 30px;
                TouchArea {
                    clicked => {
                        is-adding-event = false;
                    }
                }
            }
        }
        if is-editing-event : editEvent := VerticalLayout {
            spacing: 10px;
            in-out property <string> uid: "";
//--------------Title
            HorizontalLayout {
                MyText {text: "Event title:"; vertical-alignment: center;}
                title-input2 := LineEdit {
                    placeholder-text: "My event"; 
                    width: 250px;
                    height: 30px;
                }
            }
//---------------Date
            HorizontalLayout {
                MyText {text: "Date:";vertical-alignment: center;}
                addEventMain2 := HorizontalLayout {
                    out property <int> year: year-input2.text.to-float();
                    out property <int> month: month-input2.text.to-float();
                    out property <int> day: day-input2.text.to-float();

                    out property <int> max-days: 
                    month == 2 ? (is-leap-year ? 29 : 28) :
                    (month == 4 || month == 6 || month == 9 || month == 11) ? 30 : 31;

                    private property <bool> is-leap-year: 
                        mod(year, 4) == 0 && (mod(year, 100) != 0 || mod(year, 400) == 0);

                    in-out property <bool> is-valid-date:
                    (year-input2.text.character-count == 4 &&
                    year >= 2026 && year <=  2100 &&
                    month >= 1 && month <= 12 && day >= 1 && day <= max-days)
                    || (year-input2.text.character-count == 0 && day-input2.text.character-count == 0
                        && month-input2.text.character-count == 0);

                    day-input2 := LineEdit {
                        placeholder-text: "DD";
                        width: 80px;
                        height: 30px;
                    }
                    month-input2 := LineEdit {
                        placeholder-text: "MM";
                        width: 80px;
                        height: 30px;
                    }
                    year-input2 := LineEdit {
                        placeholder-text: "YYYY";
                        width: 80px;
                        height: 30px;
                    }
                }
            }
            HorizontalLayout {
                MyText {text: "Starts:";vertical-alignment: center;}
                beg-input2 := HorizontalLayout {
                    in-out property <int> hours: beg-hour2.text.to-float();
                    in-out property <int> mins: beg-hour2.text.to-float();
                    in-out property <bool> is-valid:
                    hours >= 0 && hours < 24 
                    && mins >= 0 && mins < 60;

                    beg-hour2 := LineEdit {
                        width: 80px;
                        height: 30px;
                        placeholder-text: "hh";
                    }
                    
                    beg-min2 := LineEdit {
                        width: 80px;
                        height: 30px;
                        placeholder-text: "mm";
                    }
                }
            }
            HorizontalLayout {
                MyText {text: "Ends:";vertical-alignment: center;}
                end-input2 := HorizontalLayout {
                    in-out property <int> hours: beg-hour2.text.to-float();
                    in-out property <int> mins: beg-hour2.text.to-float();
                    in-out property <bool> is-valid:
                    hours >= 0 && hours < 24 
                    && mins >= 0 && mins < 60;

                    end-hour2 := LineEdit {
                        placeholder-text: "hh";
                        width: 80px;
                        height: 30px;
                    }
                    
                    end-min2 := LineEdit {
                        width: 80px;
                        height: 30px;
                        placeholder-text: "mm";
                    }
                }
            } 
            addSubmit2 := Rectangle {
                MyText {text: beg-input2.is-valid && end-input2.is-valid && addEventMain2.is-valid-date ?
                    "Submit" : "Incorrect format";}
                background: beg-input2.is-valid && end-input2.is-valid && addEventMain2.is-valid-date ? 
                AppPalette.secondary-color : #c82323;
                border-radius: 5px;
                width: 100px;
                height: 30px;
                TouchArea {
                    clicked => {
                        if(beg-input2.is-valid && end-input2.is-valid && addEventMain2.is-valid-date){
                            if(beg-hour2.text.character-count == 0 || beg-min2.text.character-count == 0){
                                if(end-hour2.text.character-count == 0 || end-min2.text.character-count == 0){
                                    change_event(editEvent.uid, title-input2.text, day-input2.text.to-float(), month-input2.text.to-float(), year-input2.text.to-float(),
                                    -1,-1,-1,-1);
                                }else{
                                    change_event(editEvent.uid, title-input2.text, day-input2.text.to-float(), month-input2.text.to-float(), year-input2.text.to-float(),
                                    -1,-1, end-hour2.text.to-float(), end-min2.text.to-float());
                                }
                            }else if(end-hour2.text.character-count == 0 || end-min2.text.character-count == 0){
                                change_event(editEvent.uid, title-input2.text, day-input2.text.to-float(), month-input2.text.to-float(), year-input2.text.to-float(),
                                    beg-hour2.text.to-float(), beg-min2.text.to-float(), -1, -1);
                            }else{
                                change_event(editEvent.uid, title-input2.text, day-input2.text.to-float(), month-input2.text.to-float(), year-input2.text.to-float(),
                                    beg-hour2.text.to-float(), beg-min2.text.to-float(), end-hour2.text.to-float(), end-min2.text.to-float());
                            }
                            is-editing-event = false;
                        }
                    }
                }
            }
            Rectangle {
                MyText {text: "Cancel"; horizontal-alignment: center;}
                background: AppPalette.primary-color ;
                border-radius: 5px;
                width: 60px;
                height: 30px;
                TouchArea {
                    clicked => {
                        is-editing-event = false;
                    }
                }
            }
        }
    }
    Rectangle{
        horizontal-stretch: 1;
    }
    VerticalLayout {
        padding-top: -50px;
        HorizontalLayout{
            alignment: center;
            spacing: 10px;
            padding-bottom: 10px;
            Rectangle{
                MyText {
                    text: "<";
                }
                width: 20px;
                height: 20px;
                border-radius: 12px;
                background: AppPalette.primary-color;
                TouchArea {
                    clicked => {
                        get_events(month - 1, year);
                    }
                }
            }
            MyText{ //need to center
                text: month_name;
                horizontal-alignment: center;
                vertical-alignment: center;
                font-weight: 600;
                font-size: 25px;
            }Rectangle{
                MyText {
                    text: ">";
                }
                width: 20px;
                height: 20px;
                border-radius: 8px;
                background: AppPalette.primary-color;
                TouchArea {
                    clicked => {
                        get_events(month+1, year)
                    }
                }
            }
        }
        HorizontalLayout{
            spacing: 5px;
            MyText{
                text: "Sunday";
                width: 80px;
                font-weight: 600;
                horizontal-alignment: center;
            }
            MyText{
                text: "Monday";
                width: 80px;
                font-weight: 600;
                horizontal-alignment: center;
            }
            MyText{
                text: "Tuesday";
                width: 80px;
                font-weight: 600;
                horizontal-alignment: center;
            }
            MyText{
                text: "Wednesday";
                width: 80px;
                font-weight: 600;
                horizontal-alignment: center;
            }
            MyText{
                text: "Thursday";
                width: 80px;
                font-weight: 600;
                horizontal-alignment: center;
            }
            MyText{
                text: "Friday";
                width: 80px;
                font-weight: 600;
                horizontal-alignment: center;
            }
            MyText{
                text: "Saturday";
                width: 80px;
                font-weight: 600;
                horizontal-alignment: center;
            }
        }
        GridLayout{
            spacing: 5px;
            for day in days : Rectangle {
                row: day.row_idx;
                col: day.col_idx;
                width: 80px;
                height: 80px;
                MyText{
                    text: day.day-of-month;
                }
                if day.has-event : Rectangle{
                    border-radius: 20px;
                    border-width: 1px;
                    border-color: AppPalette.secondary-color;
                }
                TouchArea {
                    clicked => {
                        is-adding-event = true;
                        is-editing-event = false;
                        //postaviti datum na izabrani
                    }
                }
            }
        }
    }
    Rectangle {}
}