import { AppPalette } from "palette.slint";

export component MyText inherits Text {
    color: AppPalette.text-color;
    font-size: 14px;
    font-family: "Arial";
}

export component MyButton inherits Rectangle {
    in property <string> text: "";
    in property <color> button-color: AppPalette.primary-color;
    in property <color> text-color: #383838;
    
    callback clicked;

    width: 120px;
    height:  40px;
    border-radius: 8px;
    border-width: 1px;
    border-color: self.background.darker(20%);
    
    animate background { duration: 150ms; }

    background: touch.pressed ? button-color.darker(30%) : 
                touch.has-hover ? button-color.brighter(20%) : 
                button-color;

    HorizontalLayout {
        padding-left: 20px;
        padding-right: 20px;
        padding-top: 10px;
        padding-bottom: 10px;
        alignment: center;

        Text {
            text: root.text;
            color: root.text-color;
            font-size: 14px;
            font-weight: 600;
            vertical-alignment: center;
            overflow: elide;
        }
    }
    touch := TouchArea {
        clicked => {
            root.clicked();
        }
    }
}

export component TaskHeader inherits Rectangle {
    in property <string> text: "";
    in property <color> button-color: AppPalette.bg-color;
    in property <color> text-color: AppPalette.text-color;
    
    callback clicked;

    width: 120px;
    height: 30px;
    border-radius: 8px;
    border-width: 1px;
    
    border-color: touch.pressed ? AppPalette.secondary-color.darker(30%) : 
                touch.has-hover ? AppPalette.secondary-color.brighter(20%) : 
                AppPalette.secondary-color;

    HorizontalLayout {
        padding-left: 10px;
        padding-right: 10px;
        padding-top: 5px;
        padding-bottom: 5px;
        alignment: center;

        Text {
            text: root.text;
            color: root.text-color;
            font-size: 14px;
            font-weight: 600;
            vertical-alignment: center;
            overflow: elide;
        }
    }

    touch := TouchArea {
        clicked => {
            root.clicked();
        }
    }
}

export component FoNLogo inherits Image {
    source: AppPalette.is-dark ? @image-url("fonlogo-dark.png") : @image-url("fonlogo-light.png");
    width: 80px;
    height: 80px;
}