import { AppPalette } from "palette.slint";
import { LineEdit } from "std-widgets.slint";
import { MyText } from "commons.slint";
export enum FolderStatus {
    None, Invalid, Valid, Checking  
}

export component FolderPicker inherits VerticalLayout{
    in-out property <string> folder-path: "";
    in-out property <FolderStatus> folder-status: FolderStatus.None;
    in-out property <string> folder-error-message: "";
    
    //add needed functions here, unsure what's necessary
    callback browse-clicked(); //we need to see what it returns
    callback check-manually(string);
    HorizontalLayout{
        padding-top: 10px;
        alignment:center;
        MyText{
            text: "Choose your work folder";
            font-size: 16px;
            color: AppPalette.text-color;
        }
    }
    HorizontalLayout {
        folder-path-input := LineEdit {
            text <=> root.folder-path;
            placeholder-text: "/path/to/your/project";
            accepted(text) => {
                folder-path = self.text;
                check-manually(root.folder_path);
            }
        }
        Rectangle {
            width: 90px;
            height: 40px;
            background: AppPalette.primary-color;
            border-radius: 6px;
            HorizontalLayout {
                alignment: center;
                Image {} //add a lil directory img
                padding-top : 13px;
                MyText {text: "Browse";}
            }
            TouchArea {
                clicked => {browse-clicked();}
            }
        }
    }
    if folder-status != FolderStatus.None : HorizontalLayout {
        spacing: 7px;
        padding-top: 5px;
        if folder-status == FolderStatus.Checking : MyText {
            text: "Checking...";
        }
        if folder-status == FolderStatus.Valid : MyText {
            text: "Folder found and accessible.";
        }
        if folder-status == FolderStatus.Invalid : MyText {
            text: folder-error-message;
        }
    }
}

/*
_________________________
|   ___________
|   |     folder    | {check} -> idfk
|   {{{{{}}}}}
| status ????????

*/