import { AppPalette }                    from "palette.slint";
import { MyButton, FoNLogo, MyText }                      from "commons.slint";
import { SlintTask, TaskView }           from "tasks.slint";
import { SlintCalendarEvent, CalendarView, DateInfo } from "calendar.slint";
import { SlintNote, SlintCategory, NotesView } from "notes.slint";

export component AppWindow inherits Window{
    title: "Form of Notes";
    icon: @image-url("fonlogo-light.png");
    min-width: 1600px;
    min-height: 900px;

    in-out property <int> current-tab: 0; //tasks, calendar, notes

    callback change-folder(string);


    // Tasks 
    callback get-tasks <=> task-view.get-tasks;
    callback modify-task <=> task-view.modify-task;
    callback update-time <=> task-view.update-time;
    callback finish-task <=> task-view.finish-task;
    callback delete-task <=> task-view.delete-task;
    callback is-valid-date <=> task-view.is-valid-date;
    in-out property <[SlintTask]> tasks <=> task-view.tasks;

    // Calendar
    callback add-event <=> calendar-view.add_event;
    callback change-event <=> calendar-view.change_event;
    callback get-events <=> calendar-view.get_events;
    callback delete-event <=> calendar-view.delete_event;
    
    in-out property <bool> is-deadline-valid <=> task-view.is-deadline-valid;
    in-out property <[SlintCalendarEvent]> events <=> calendar-view.events;
    in-out property <[DateInfo]> calendar-days <=> calendar-view.days;
    in-out property <int> calendar-month <=> calendar-view.month;
    in-out property <int> calendar-year <=> calendar-view.year;
    in-out property <string> calendar-month-name <=> calendar-view.month_name;

    //Notes
    callback new-note <=> notes-view.new-note;
    callback add-category <=> notes-view.add-category;
    callback select-category <=> notes-view.select-category;
    callback select-note <=> notes-view.select-note;
    callback change-note-title <=> notes-view.change-note-title;
    callback change-note-content <=> notes-view.change-note-content;
    //callback save-note <=> notes-view.save-note;
    callback delete-note <=> notes-view.delete-note;

    in-out property <[SlintCategory]> categories <=> notes-view.categories;
    in-out property <[SlintNote]> notes <=> notes-view.notes;

    in-out property <string> selected-note-id <=> notes-view.selected-note-id;

    in-out property <string> editing-title <=> notes-view.editing-title;
    in-out property <string> editing-content <=> notes-view.editing-content;

    background: AppPalette.bg-color;
    default-font-family: "Arial";
    default-font-size: 16px;

    VerticalLayout {
        header := VerticalLayout{
            height: 250px;
            VerticalLayout {
                spacing: 10px;
                padding: 10px;

                HorizontalLayout {
                    spacing: 10px;
                    HorizontalLayout {
                        alignment: start;
                        FoNLogo{
                            width: 120px;
                            height: 120px;
                        }
                        MyText {
                            text: "My Workspace";
                            vertical-alignment: center;
                            font-size: 25px;
                        }
                    }
                    VerticalLayout {
                    alignment: center;
                    HorizontalLayout {
                        alignment: end;
                        spacing: 5px;
                        MyButton {
                            width: 200px;
                            text: "Change work folder";
                            clicked => {
                            //    root.change-folder();
                            }
                        }
                        MyButton {
                            text: AppPalette.is_dark ? "Light Mode" : "Dark Mode";
                            clicked => {AppPalette.is-dark = !AppPalette.is-dark;}
                        }
                    }
                    }
                }

                HorizontalLayout {
                    alignment: center;
                    spacing: 40px;
                    MyButton {
                        text: "Tasks";
                        button-color: root.current-tab == 0 ? AppPalette.primary-color : AppPalette.secondary-color;
                        clicked => {root.current-tab = 0;}
                    }
                    MyButton {
                        text: "Calendar";
                        button-color: root.current-tab == 1 ? AppPalette.primary-color : AppPalette.secondary-color;
                        clicked => {root.current-tab = 1;}
                    }
                    MyButton {
                        text: "Notes";
                        button-color: root.current-tab == 2 ? AppPalette.primary-color : AppPalette.secondary-color;
                        clicked => {root.current-tab = 2;}
                    }
                }
            }
        }
        Rectangle {
            vertical-stretch: 1;
            horizontal-stretch: 1;

            task-view := TaskView {
                width: 100%;
                height: 100%;
                visible: root.current-tab == 0;
            }

            calendar-view := CalendarView {
                width: 100%;
                height: 100%;
                visible: root.current-tab == 1;
            }

            notes-view := NotesView {
                width: 100%;
                height: 100%;
                visible: root.current-tab == 2;
            }
        }
    }
}