import { AppPalette }                    from "palette.slint";
import { MyButton, FoNLogo }                      from "commons.slint";
import { SlintTask, TaskView }           from "tasks.slint";
import { SlintCalendarEvent, CalendarView } from "calendar.slint";

export component AppWindow inherits Window{
    title: "Form of Notes";
    icon: @image-url(""); //dodati logo
    preferred-width: 800px;
    preferred-height: 600px;
    
    in-out property <int> current-tab: 0; //tasks, calendar, notes
    in-out property <[SlintTask]> tasks: [];
    in-out property <[SlintCalendarEvent]> events: [];

    callback import_workspace(string);
    callback get-tasks(int) -> [SlintTask];
    callback get-calendar() -> [SlintCalendarEvent];
    callback change-folder(string);
    callback update-time(int, string);

    background: AppPalette.bg-color;
    default-font-family: "Arial";
    default-font-size: 16px;

    VerticalLayout {
        header := Rectangle{
            property <string> workspace-name: "My workspace";
            in-out property <bool> is-editing: false;

            height: 120px;
            VerticalLayout {
                spacing: 10px;
                padding: 10px;

                HorizontalLayout {
                    spacing: 10px;
                    HorizontalLayout {
                        alignment: start;
                        FoNLogo{}
                        Text {
                            text: "My Workspace";
                        }
                    }
                    HorizontalLayout {
                        alignment: end;
                        //export img
                        spacing: 5px;
                        MyButton {
                            text: "Change Workplace";
                            clicked => {
                            //    root.change-folder();
                            }
                        }
                        MyButton {
                            text: AppPalette.is_dark ? "Light Mode" : "Dark Mode";
                            clicked => {AppPalette.is-dark = !AppPalette.is-dark;}
                        }
                    }
                }

                HorizontalLayout {
                    alignment: center;
                    horizontal-stretch: 1; // pomera ih da razmak bude jednak
                    MyButton {
                        text: "Tasks";
                        button-color: root.current-tab == 0 ? AppPalette.primary-color : AppPalette.secondary-color;
                        clicked => {
                            root.current-tab = 0;
                            root.tasks = root.get-tasks(5);
                        }
                    }
                    MyButton {
                        text: "Calendar";
                        button-color: root.current-tab == 1 ? AppPalette.primary-color : AppPalette.secondary-color;
                        clicked => {
                            root.current-tab = 1;
                            root.events = root.get-calendar();
                        }
                    }
                    MyButton {
                        text: "Notes";
                        button-color: root.current-tab == 2 ? AppPalette.primary-color : AppPalette.secondary-color;
                        clicked => {root.current-tab = 2;}
                    }
                }
            }
            Rectangle {
                y: header.height - 2px;
                width: header.width;
                height: 2px;
                background: @linear-gradient(90deg, 
                    AppPalette.primary-color.darker(60%) 10%,
                    AppPalette.primary-color 50%,
                    AppPalette.primary-color.darker(60%) 90%);
            }
        }
        if root.current-tab == 0 : TaskView {
            tasks: root.tasks;
            get-tasks(s) => {root.get-tasks(s)}
            update-time(id, t) => {root.update-time(id, t)}
        }
        if root.current-tab == 2 : CalendarView {

        }
        /*if root.current-tab == 2 : NotesView {

        }*/
    }
}