import { Button, LineEdit, TextEdit, ListView, ScrollView } from "std-widgets.slint";
import { AppPalette } from "palette.slint";
import { TaskHeader, MyButton, MyText } from "commons.slint";

export struct SlintCategory {
    id: string,
    name: string,
    color: string,
}

export struct SlintNote {
    id: string,
    title: string,
    content: string,
    category-ids: [string],
    last-update: string,
}

component NoteListItem {
    in property <string> note_id;
    in property <string> title;
    in property <[string]> category-ids;
    in property <bool> selected;
    callback clicked;

    touch := TouchArea { clicked => { root.clicked(); } }

    Rectangle {
        background: root.selected ? AppPalette.secondary-color.darker(10%) : (touch.has-hover ? AppPalette.secondary-color.brighter(10%) : transparent);
        border-radius: 6px;
        animate background { duration: 150ms; }

        VerticalLayout {
            padding: 10px;
            spacing: 6px;

            Text {
                text: root.title == "" ? "Untitled Note" : root.title;
                font-size: 15px;
                font-weight: root.selected ? 600 : 400;
                color: AppPalette.is-dark ? white : #333333;
            }
            
            HorizontalLayout {
                spacing: 4px;
                alignment: start;
                for id in root.category-ids : Rectangle {
                    width: 10px;
                    height: 10px;
                    border-radius: 5px;
                    background: AppPalette.primary-color;
                }
            }
        }
    }
}

component CategoryTag {
    in property <string> name;
    in property <string> color;
    in property <bool> active;
    callback clicked;

    touch := TouchArea { clicked => { root.clicked(); } }

    Rectangle {
        background: root.active ? AppPalette.primary-color : AppPalette.secondary-color;
        border-radius: 12px;
        border-width: 1px;
        border-color: root.active ? transparent : AppPalette.primary-color.darker(10%);
        animate background { duration: 100ms; }

        Text {
            text: root.name;
            font-size: 13px;
            color: root.active ? white : (AppPalette.is-dark ? #dddddd : #333333);
            padding: 12px;
        }
    }
}

export component NotesView inherits HorizontalLayout {
    callback new-note();
    callback add-category(string);
    callback select-category(string);
    callback select-note(string);
    callback change-note-title(string, string);
    callback change-note-content(string, string);
    //callback save-note();
    callback delete-note(string);

    in-out property <[SlintCategory]> categories: [];
    in-out property <[SlintNote]> notes: [];
    in property <string> active-category-id: "all";
    in-out property <string> selected-note-id: "-1";
    
    in-out property <string> editing-title: "";
    in-out property <string> editing-content: "";

    spacing: 0px;

    Rectangle {
        width: 500px;
        background: AppPalette.bg-color.darker(5%);

        VerticalLayout {
            padding: 12px;
            spacing: 12px;
            
            HorizontalLayout {
                spacing: 8px;
                height: 35px;
                
                MyButton {
                    width: 230px;
                    text: "New Note";
                    clicked => { root.new-note(); }
                }
                
                MyButton {
                    width: 230px;
                    text: form-area.visible ? "Cancel" : "Add Category";
                    clicked => {
                        form-area.visible = !form-area.visible;
                        form-area.new-name = "";  
                    }
                }
            }
            
            form-area := Rectangle {
                visible: false;
                height: self.visible ? 150px : 0px;
                animate height { duration: 150ms; easing: ease-in-out; }
                clip: true;
                background: AppPalette.bg-color.darker(10%);
                border-radius: 8px;
                border-width: 1px;
                border-color: AppPalette.primary-color;

                in-out property <string> new-name: "";

                VerticalLayout {
                    padding: 12px;
                    spacing: 10px;

                    HorizontalLayout {
                        spacing: 8px;
                        MyText {
                            text: "Category Name:";
                            color: AppPalette.text-color;
                            width: 170px;
                            vertical-alignment: center;
                        }
                        LineEdit {
                            placeholder-text: "New Category";
                            width: 200px;
                            height: 50px;
                            text <=> form-area.new-name;
                            edited(val) => { form-area.new-name = val; }
                        }
                    }

                    HorizontalLayout {
                        alignment: end;
                        MyButton {
                            text: "Add";
                            button-color: form-area.new-name == "" ?
                                AppPalette.primary-color.darker(40%) :
                                AppPalette.primary-color;
                            clicked => {
                                if form-area.new-name != "" {
                                    root.add-category(form-area.new-name);
                                    
                                    form-area.new-name = "";
                                    form-area.visible = false;
                                }
                            }
                        }
                    }
                }
            }

            Text { 
                text: "FILTERS"; 
                font-weight: 700; 
                color: AppPalette.is-dark ? #888888 : #666666; 
                font-size: 11px; 
            }
            
            HorizontalLayout {
                ScrollView {
                    height: 70px;

                    HorizontalLayout {
                        width: self.preferred-width; 
                        spacing: 6px;
            
                        CategoryTag {
                            name: "All Notes";
                            active: root.active-category-id == "all";
                            clicked => { root.select-category("all"); }
                        }
                        for cat in root.categories : CategoryTag {
                            name: cat.name;
                            color: cat.color;
                            active: cat.id == root.active-category-id;
                            clicked => { root.select-category(cat.id); }
                        }
                    }
                }
            }

            Rectangle { height: 1px; background: AppPalette.secondary-color; }

            Text { 
                text: "NOTES"; 
                font-weight: 700; 
                color: AppPalette.is-dark ? #888888 : #666666; 
                font-size: 11px; 
            }
            
            ListView {
                for note[index] in root.notes : NoteListItem {
                    note_id: note.id;
                    title: note.title;
                    category-ids: note.category-ids;
                    selected: note.id == root.selected-note-id;
                    clicked => {
                        root.select-note(note.id); 
                    }
                }
            }
        }
    }

    Rectangle {
        horizontal-stretch: 1;

        if root.selected-note-id != "-1" : VerticalLayout {
            padding: 20px;
            spacing: 15px;

            LineEdit {
                text <=> root.editing-title;
                placeholder-text: "Enter Note Title...";
                font-size: 22px;
                height: 40px;
                edited(text) => { 
                    root.editing-title = text;
                    root.change-note-title(root.selected-note-id, text); 
                }
            }

            Rectangle { height: 1px; background: AppPalette.secondary-color; }

            TextEdit {
                text <=> root.editing-content;
                font-size: 16px;
                edited(text) => {
                    root.editing-content = text;
                    root.change-note-content(root.selected-note-id, text); 
                }
            }

            HorizontalLayout {
                spacing: 12px;
                height: 35px;
                alignment: end;

                /*MyButton {
                    text: "Save Note";
                    width: 120px;
                    clicked => { root.save-note(); }
                }*/

                MyButton {
                    text: "Delete Note";
                    width: 150px;
                    clicked => { 
                        root.delete-note(root.selected-note-id);
                    }
                }
            }
        }

        if root.selected-note-id == "-1" : VerticalLayout {
            alignment: center;
            Text {
                text: "Select a note to view or edit content.";
                horizontal-alignment: center;
                font-size: 16px;
                color: AppPalette.is-dark ? #777777 : #999999;
            }
        }
    }
}